---
# tasks file for base

- name: Set hostname
  hostname: 
    name: "{{ ec2_tag_Name }}"

- name: Adjust /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1'
    line: "127.0.0.1 localhost {{ ec2_tag_Name }}"
    backup: yes

- name: Install useful packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - aptitude
    - sysstat
    - python-pip
  tags:
    - install_pkgs

- name: Update package lists
  apt:
    update_cache: yes
    cache_valid_time: 36000

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    only_upgrade: yes
  when: upgrade_pkgs is defined and upgrade_pkgs == "yes"   
