
- block:

    - name: Delete existing app directory - {{ app_dir }}
      file:
        name: "{{ app_dir }}"
        state: absent

    - name: Create app directory - {{ app_dir }}
      file:
        name: "{{ app_dir }}"
        state: directory

    - name: git clone app code
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dir }}"
        #version: master

    - name: Create python virtualenv
      command: python3.6 -m venv {{ venv_dir }}

    - name: pip install requirements.txt
      command: "{{ venv_dir }}/bin/pip install -r {{ app_dir }}/requirements.txt"

    - name: Do collectstatic
      command: "{{ venv_dir }}/bin/python {{ app_dir }}/manage.py collectstatic --noinput"

    - name: Make django db migrations
      command: "{{ venv_dir }}/bin/python {{ app_dir }}/manage.py migrate"
      when: migrate_db == "yes"

  become_user: "{{ sites_owner }}"

- name: Install nginx configuration file
  template: 
    src:  files/nginx/tdd_django_template
    dest: "/etc/nginx/sites-available/{{ env_vars[env].nginx_file }}"

- name: Make nginx symlink
  file:
    src:   "/etc/nginx/sites-available/{{ env_vars[env].nginx_file }}"
    dest:  "/etc/nginx/sites-enabled/{{ env_vars[env].nginx_file }}"
    state: link
