
- block:

    - name: Delete any old staging app directory
      file:
        name: "{{ staging_dir }}"
        state: absent

    - name: Create staging app directory
      file:
        name: "{{ staging_dir }}"
        state: directory

    - name: git clone app code
      git:
        repo: "{{ git_repo }}"
        dest: "{{ staging_dir }}"
        version: master

    - name: Create python virtualenv
      command: python3.6 -m venv {{ staging_venv_dir }}

    - name: pip install requirements.txt
      command: "{{ staging_venv_dir }}/bin/pip install -r {{ staging_dir }}/requirements.txt"

  become_user: "{{ sites_owner }}"
