---
# vars file for django-app

sites_owner: ubuntu
sites_dir: /home/{{ sites_owner }}/sites
git_repo: https://github.com/chan-alex/tdd-django

app_port: 8000

env_vars:
    staging:
        domain: tdd-python-staging.chanalex.com
        nginx_file: tdd_django_staging 


app_dir: "{{ sites_dir }}/{{ env_vars[env].domain }}"
venv_dir: "{{ app_dir }}/virtualenv"
