---
# vars file for django-app

sites_owner: ubuntu
sites_dir: /home/{{ sites_owner }}/sites


git_repo: https://github.com/chan-alex/tdd-django

staging_domain: tdd-python-staging.chanalex.com
staging_dir: "{{ sites_dir }}/{{ staging_domain }}"
staging_venv_dir: "{{ staging_dir }}/virtualenv"
